name: Lesson 6

on:
  push:
    branches:
      - lesson-6
jobs:
  function_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - name: Run functional tests
        run: npm test -- --coverage --watchAll=false
  deploy:
    needs: [function_test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - run: npm install && npm run build
      - name: Generate deployment package
        run: zip -r deploy.zip build Dockerfile
      - name: '**PLACEHOLDER** Deploy to Elastic Beanstalk'
        run: echo Placeholder for Deployment
  security_test:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Dynamic Application Security Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://hangry-web-dev.us-east-1.elasticbeanstalk.com/'
